some little things and a big thing: custom error handling

diff --git a/scripts/www b/scripts/www
--- a/scripts/www
+++ b/scripts/www
@@ -2,11 +2,10 @@
 
 DEFAULT_PORT=1313
 port=${1:-$DEFAULT_PORT}
-echo "\$port=$port"
-echo Running splunge on port $port... 
-
 logFolder="~/tmp/splunge/log"
-mkdir -p "$logFolder/"
+mkdir -p "$logFolder/" || { printf 'Unable to create log folder %s\n' "$logFolder" &>2; return; }
+echo "Running splunge on port $port & logging to $logFolder ..."
+
 
 gunicorn --bind localhost:$port \
          --access-logfile "$logFolder/access.log" \
@@ -14,4 +13,5 @@ gunicorn --bind localhost:$port \
          --workers 3 \
          --umask 007 \
          --reload \
-         splunge.app:app
+         splunge.app:app \
+         || cat "$logFolder/errors.log"
